version: '2'
services:
  gspotsyncer:
    build: .
    depends_on:
      - mongo
      - memcached
    links:
      - mongo
      - memcached
    restart: always
  mongo:
    image: mongo
    environment:
      - VIRTUAL_HOST=mongo
      - VIRTUAL_PORT=27017
    volumes:
      - ./mongo_data:/data/db
  memcached:
      image: memcached
      environment:
        - VIRTUAL_HOST=memcached