version: '2'
services:
  gspotsyncer:
    build: .
    environment:
     - APP_ENV=PROD
     - VIRTUAL_HOST=gspotsyncer.com,www.gspotsyncer.com
    depends_on:
      - mongo
      - memcached
      - jenkins
      - nginx-proxy
    links:
      - nginx-proxy
      - jenkins
    command: python runp.py
  jenkins:
    image: jenkins
    environment:
      - VIRTUAL_HOST=jenkins.gspotsyncer.com
      - VIRTUAL_PORT=8080
    volumes:
      - ./jenkins:/var/jenkins_home
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro