version: '2'
services:
  gspotsyncer:
    build: .
    depends_on:
      - mongo
      - memcached
      - nginx-proxy
    links:
      - mongo
      - memcached
      - nginx-proxy
    restart: always
  mongo:
    image: mongo
    environment:
      - VIRTUAL_HOST=mongo
      - VIRTUAL_PORT=27017
    volumes:
      - ./mongo_data:/data/db
  memcached:
      image: memcached
      environment:
        - VIRTUAL_HOST=memcached
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro