version: '2'
services:
  gspotsyncer:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/opt/gspotsyncer
    environment:
     - DB_ENV=TEST_MONGO
    command: python gspotsyncer_tests.py