version: '2'
services:
  gspotsyncer:
    build: .
    volumes:
     - .:/opt/gspotsyncer
    environment:
     - APP_ENV=TEST
     - DB_ENV=TEST_MONGO
    command: python gspotsyncer_tests.py
    restart: 'no'