version: '2'
services:
  gspotsyncer:
    build: .
    depends_on:
      - mongo
      - memcached
      - nginx-proxy
    links:
      - mongo
      - memcached
      - nginx-proxy
    restart: always
  mongo:
    image: mongo
    volumes:
      - ./mongo_data:/data/db
  memcached:
      image: memcached
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro