version: '2'
services:
  gspotsyncer:
    build: .
    depends_on:
      - mongo
      - memcached
    links:
      - mongo
      - memcached
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
  memcached:
      image: memcached