version: '2'
services:
  gspotsyncer:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/opt/gspotsyncer
  #   depends_on:
  #    - jenkins
  # jenkins:
  #   image: jenkins
  #   ports:
  #    - "49001:8080"
  #   volumes:
  #    - ./jenkins:/var/jenkins_home