version: '2'
services:
  gspotsyncer:
    build: .
    environment:
     - APP_ENV=PROD
     - VIRTUAL_HOST=gspotsyncer.com
    depends_on:
      - mongo
      - memcached
      - jenkins
    links:
      - jenkins
    command: python runp.py
  jenkins:
    image: jenkins
    environment:
      - VIRTUAL_HOST=jenkins.gspotsyncer.com
      - VIRTUAL_PORT=8080
    volumes:
      - ./jenkins:/var/jenkins_home