version: '2'
services:
  gspotsyncer:
    build: .
    ports:
     - "80:5000"
    volumes:
     - .:/opt/gspotsyncer
    depends_on:
      - mongo
    links:
      - mongo
  #    - jenkins
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
  # jenkins:
  #   image: jenkins
  #   ports:
  #    - "49001:8080"
  #   volumes:
  #    - ./jenkins:/var/jenkins_home